[package]
name = "overload"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", features = ["span-locations"] }
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"
heck = "0.4"

[dev-dependencies]
async-trait = "0.1"
